import type { VisualForm } from "../scale-data";

/**
 * The catalog's visual form is the only top-level renderer selector.
 *
 * Several forms intentionally share a silhouette family, but every form is
 * listed here so adding a catalog form cannot silently drop into a box, rock,
 * or other shape-based fallback.
 */
export const COLLECTIBLE_VISUAL_HANDLER_BY_FORM = {
  foam: "bubble",
  "field-ripple": "field-ripple",
  spark: "spark",
  string: "string",
  quark: "quark",
  hadron: "hadron",
  "nuclear-cluster": "nuclear-cluster",
  "atom-cloud": "atom",
  molecule: "molecule",
  "molecule-bent": "molecule",
  "molecule-linear": "molecule",
  protein: "protein",
  "double-helix": "double-helix",
  vesicle: "vesicle",
  antibody: "antibody",
  "virus-enveloped": "virus",
  "virus-faceted": "virus",
  bacteriophage: "bacteriophage",
  "cell-soft": "cell",
  bacterium: "cell",
  "blood-cell": "cell",
  "immune-cell": "cell",
  "plant-cell": "cell",
  neuron: "cell",
  sperm: "cell",
  ciliate: "ciliate",
  diatom: "diatom",
  pollen: "pollen",
  tardigrade: "tardigrade",
  mite: "mite",
  worm: "worm",
  fiber: "fiber",
  "dust-cluster": "dust",
  grain: "stone",
  crystal: "crystal",
  seed: "seed",
  bead: "bead",
  button: "button",
  brick: "brick",
  "bottle-cap": "bottle-cap",
  coin: "coin",
  key: "key",
  die: "die",
  pencil: "pencil",
  mug: "mug",
  book: "book",
  spoon: "spoon",
  shoe: "shoe",
  lamp: "lamp",
  chair: "chair",
  couch: "couch",
  guitar: "guitar",
  table: "table",
  screen: "screen",
  "potted-plant": "potted-plant",
  bed: "bed",
  appliance: "appliance",
  bathtub: "bathtub",
  doorway: "doorway",
  bicycle: "bicycle",
  motorcycle: "motorcycle",
  sailboat: "sailboat",
  vehicle: "vehicle",
  train: "train",
  tree: "tree",
  pool: "pool",
  house: "house",
  tower: "tower",
  bridge: "bridge",
  stadium: "stadium",
  park: "park",
  landform: "landform",
  "river-system": "river-system",
  forest: "forest",
  "weather-front": "weather-front",
  world: "world",
  "ringed-world": "ringed-world",
  asteroid: "asteroid",
  comet: "comet",
  star: "star",
  "dense-star": "dense-star",
  "orbit-system": "orbit-system",
  "star-cluster": "star-cluster",
  nebula: "nebula",
  galaxy: "galaxy",
  "galaxy-cluster": "galaxy-cluster",
  "cosmic-web": "cosmic-web",
  "cosmic-void": "cosmic-void",
  horizon: "horizon",
  "speculative-reality": "speculative-reality",
  artifact: "artifact",
} as const satisfies Record<VisualForm, string>;

export type CollectibleVisualHandler =
  (typeof COLLECTIBLE_VISUAL_HANDLER_BY_FORM)[VisualForm];

export function collectibleVisualHandlerFor(
  visualForm: VisualForm,
): CollectibleVisualHandler {
  return COLLECTIBLE_VISUAL_HANDLER_BY_FORM[visualForm];
}
