import { readFile, writeFile } from "node:fs/promises";
import { build } from "vite";

const marker = "/*__RESCUE_BUNDLE__*/";
const result = await build({
  configFile: false,
  logLevel: "silent",
  resolve: {
    alias: {
      $lib: new URL("../src/lib", import.meta.url).pathname,
    },
  },
  build: {
    write: false,
    lib: {
      entry: new URL("../src/rescue-entry.ts", import.meta.url).pathname,
      formats: ["iife"],
      name: "QuantamariRescue",
    },
  },
});

const output = Array.isArray(result) ? result[0] : result;
const chunk = output.output.find((entry) => entry.type === "chunk");
if (!chunk) throw new Error("The rescue build produced no JavaScript.");

const safeScript = chunk.code
  .replace(/<\/script/gi, "\\x3C/script")
  .replace(/<!--/g, "\\x3C!--")
  .replace(/<script/gi, "\\x3Cscript");
const template = await readFile(
  new URL("../src/rescue.template.html", import.meta.url),
  "utf8",
);
if (!template.includes(marker)) {
  throw new Error("The rescue template has no bundle marker.");
}
const html = template
  .replace(marker, () => safeScript)
  .replace(
    "<!doctype html>",
    "<!doctype html>\n<!-- Generated by scripts/build-rescue.mjs. -->",
  );
await writeFile(
  new URL("../static/rescue.html", import.meta.url),
  html,
  "utf8",
);
console.log(
  `built static/rescue.html (${Math.ceil(Buffer.byteLength(html) / 1024)} KB, no runtime imports)`,
);
